Update Chia-Docker.yml

diff --git a/.github/workflows/Chia-Docker.yml b/.github/workflows/Chia-Docker.yml
--- a/.github/workflows/Chia-Docker.yml
+++ b/.github/workflows/Chia-Docker.yml
@@ -1,41 +1,51 @@
-name: Build official Chia Docker Image
+name: Build Image
 
-on:
-  push:
-    branches:
-      - master
-  release:
-    types: [published, created, edited]
-  workflow_dispatch:
-    inputs:
-      upstream_branch:
-        description: 'chia branch name to use'
-        required: true
-        default: 'master'
-      image_tag:
-        description: 'special tag for this image build'
-        required: true
-        default: 'latest'
+on: [push, pull_request, workflow_dispatch]
+
+env:
+  ENDPOINT: "edifus/chia"
+  BRANCH: "master"
 
 jobs:
-  docker_build_and_publish:
+  build:
     runs-on: ubuntu-latest
     steps:
+      - uses: actions/checkout@v2.3.3
+
+      - name: Build image
+        run: |
+          docker build --no-cache -t ${{ github.sha }} .
+      - name: Tag image
+        run: |
+          docker tag ${{ github.sha }} ${ENDPOINT}
+          docker tag ${{ github.sha }} ${ENDPOINT}:${{ github.sha }}
+          docker tag ${{ github.sha }} ghcr.io/${ENDPOINT}
+          docker tag ${{ github.sha }} ghcr.io/${ENDPOINT}:${{ github.sha }}
+      - name: Credential check
+        run: |
+          echo "CR_USER=${{ secrets.CR_USER }}" >> $GITHUB_ENV
+          echo "CR_PAT=${{ secrets.CR_PAT }}" >> $GITHUB_ENV
+          echo "DOCKERUSER=${{ secrets.DOCKERUSER }}" >> $GITHUB_ENV
+          echo "DOCKERPASS=${{ secrets.DOCKERPASS }}" >> $GITHUB_ENV
+          if [[ "${{ secrets.CR_USER }}" == "" && "${{ secrets.CR_PAT }}" == "" && "${{ secrets.DOCKERUSER }}" == "" && "${{ secrets.DOCKERPASS }}" == "" ]]; then
+            echo "::error::Push credential secrets missing."
+            echo "::error::You must set either CR_USER & CR_PAT or DOCKERUSER & DOCKERPASS as secrets in your repo settings."
+            echo "::error::See https://github.com/linuxserver/docker-mods/blob/master/README.md for more information/instructions."
+            exit 1
+          fi
       - name: Login to GitHub Container Registry
-        uses: docker/login-action@v1
-        with:
-          registry: ghcr.io
-          username: ${{ github.actor }}
-          password: ${{ secrets.ADMIN_PAT }}
-
-      - name: Check out the repo
-        uses: actions/checkout@v2
-
-      - name: Docker Prune
-        run: docker system prune --all
-
-      - name: Build docker image
-        run: docker build --no-cache --build-arg BRANCH=${{ github.event.inputs.upstream_branch }} -t ghcr.io/${{ github.actor }}/chia:${{ github.event.inputs.image_tag }} .
-
-      - name: Push to github packages
-        run: docker push ghcr.io/${{ github.actor }}/chia:${{ github.event.inputs.image_tag }}
+        if: ${{ env.CR_USER && env.CR_PAT }}
+        run: |
+          echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ secrets.CR_USER }} --password-stdin
+      - name: Push tags to GitHub Container Registry
+        if: ${{ env.CR_USER && env.CR_PAT }}
+        run: |
+          docker push ghcr.io/${ENDPOINT}
+ #     - name: Login to DockerHub
+ #       if: ${{ env.DOCKERUSER && env.DOCKERPASS }}
+ #       run: |
+ #         echo ${{ secrets.DOCKERPASS }} | docker login -u ${{ secrets.DOCKERUSER }} --password-stdin
+ #     - name: Push tags to DockerHub
+ #       if: ${{ env.DOCKERUSER && env.DOCKERPASS }}
+ #       run: |
+ #         docker push ${ENDPOINT}
